### ISSUE TITLE
Concurrent usage?

### ISSUE THREAD

**Issue by xeoncross** [jorbs/stellar-keypair-tool#1]
I'm getting at least 20% faster generation per-core using this library than I am using the [official Go library](https://github.com/stellar/go/blob/master/keypair/main.go) (which this [other key-generation lib is using](https://github.com/0intro/stellar-keypairs/blob/master/main.go)). However, it's trivial to use go routines to create more workers per CPU.

Do you have any plans for multiple CPUs, or is the source of random fine to simply spawn multiple instances?

**Comment by jorbs** [comment]
Currently I'm working on a multi-threaded implementation. So that you can pass as parameter the number of threads to find the search term. If that value isn't provided, then the tool will calculate that number automatically. I've create #2 to this.

**Comment by jorbs** [comment]
@Xeoncross would you like to make a PR for this? I have half of the code ready...

**Comment by xeoncross** [comment]
Sorry, I don't understand. I do not have a repo to pull from/to. I was comparing this C++ version to the Go version.

**Comment by jorbs** [comment]
Gotcha!

**Comment by jorbs** [comment]
@Xeoncross the concurrency implementation is finished. let me know if you intend to do a new round of comparison.

**Comment by xeoncross** [comment]
Awesome. Since my machine and yours are different I threw a little multicore demo together for you to compare against: https://gist.github.com/Xeoncross/15c5a135352ec1ed76145875dffd86b5

I get about 42,000/s on an older Core i5

**Comment by jorbs** [comment]
Here I get ~32,000/s on a 2,9 GHz Intel Core i5.

**Comment by xeoncross** [comment]
`157942 tries in 2.17614s using 4 threads` so about 72k/s plus the added string comparison you are doing. So almost 2x as fast as the go version for me (42k/s).
