### ISSUE TITLE
Replace strong random source with pseudo random?

### ISSUE THREAD

**Issue by xeoncross** [jorbs/stellar-keypair-tool#4]
We are trying millions of keys. Wouldn't picking a strong random seed, then doing deterministic randomness after that be a lot faster than reading new crypto-strength randomness each loop?

This might be a bad idea, but could be worth potentially large speed increases.

**Comment by jorbs** [comment]
The `NaCl` uses internally `/dev/random` to generate random numbers. I may agree with you since for each loop iteration the library allocates resources opening that file. One solution would be use the `arc4random` functions (https://linux.die.net/man/3/arc4random). After I finish the concurrency implementation I’ll take a look into this.

**Comment by jorbs** [comment]
Here an approach. I could remove `libsodium` from the project and use `SUPERCOP EdDSA25519` implementation (https://ed25519.cr.yp.to/software.html). So instead of use its `randombytes` function I could use `arc4random_buf`. I'll make some tests.

**Comment by xeoncross** [comment]
Two things:

1. The vanity keys created may be much more predictable
2. The distribution of keys tried may be limited to less than the full key spectrum

Both of these could be problems so I would be weary about moving off libsodium for this.

**Comment by jorbs** [comment]
The `arc4random` man page states:

```These functions use a cryptographic pseudo-random number generator to generate high quality random bytes very quickly.  One data pool is used for all consumers in a process, so that consumption under program flow can act as additional stirring. The subsystem is re-seeded from the kernel random number subsystem on a regular basis, and also upon fork(2).```

So going with it is a good approach.
